name: sdss_catl_utils

channels:
  - astropy
  - conda-forge

dependencies:
  - python>=3.6
  - astropy
  - Cython
  - matplotlib
  - numpy
  - h5py
  - pandas
  - scipy
  - scikit-learn>=0.19.1
  - sphinx-astropy
  - pip
  - pip:
    - GitPython
    - cosmo-utils>=0.1.56
